### ISSUE TITLE
Inclusion/exclusion criteria of indicators

### ISSUE THREAD

**Issue by MikeJohnPage** [humaniverse/healthindexscotland#40]
For the unresolved indicators in the metadata file there appears to be three main issues which need resolving:

**1. Proxy indicators need to be found for some indicators** 
This includes the indicators: children in state care, low pay, difficulty completing activities of daily living, atrial fibrillation, heart disease, arterial disease, stroke & TIA and public green space. For these indicators, I don't feel qualified to comment on whether proxies exist and whether the ones already found are appropriate. For this I think the BRC's domain expertise is required. @CatReid is this something you are able to tackle?

**2. Population weighted scores**
The scores for healthy life expectancy in men and women needed combining into a single population weighted score. I have completed this in [this](https://github.com/humaniverse/healthindexscotland/pull/39) PR.

**3. Health Board data needs aggregating to local authority data**
This includes the indicators: sexual health, self-harm, diabetes, osteoporosis, rheumatoid arthritis, COPD and patients offered acceptable GP practice appointments.

I couldn't find a clear answer on whether health boards are coterminous with local authorities. I attempted to review the boundary files, and from this, it seems that they do align:

```r
library(dplyr)
library(stringr)
library(leaflet)
library(geographr)
library(ggplot2)

ggplot() +
  geom_sf(
    data = filter(boundaries_ltla21, str_detect(ltla21_code, "^S")),
    linetype = "dashed",
    linewidth = .3,
    colour = "red"
  ) +
  geom_sf(data = boundaries_hb19, alpha = 0) +
  theme_minimal()

# Interactive map
leaflet() |>
  addTiles() |>
  addPolygons(
    data = boundaries_hb19,
    fillColor = "rgb(255, 179, 104)",
    weight = 1,
    group = "Health Boards"
  ) |>
  addPolygons(
    data = filter(boundaries_ltla21, str_detect(ltla21_code, "^S")),
    fillColor = "rgb(14, 15, 15)",
    weight = 1,
    group = "Local Authorities"
  ) |> 
  addLayersControl(baseGroups = c("Health Boards", "Local Authorities"))
```
<img width="922" alt="Screenshot 2024-11-14 at 13 11 15" src="https://github.com/user-attachments/assets/d38f547d-a479-42b8-a7fe-b0183e1015e5">

So one option we have is to apply the health board scores to all the local authorities that sit within it. But this approach doesn't seem valid (and I can't find any methodology to support it). Doing so would assume that the local authorities within the same health board have similar health outcomes, which we know can certainly not be the case. A better approach would be to try and find data at a smaller level (e.g., data zone) and then aggregate up. But, I doubt the data is available for all the missing indicators.

I would strip the indicators with HB only data, and keep a smaller subset of indicators in the domain. Or aggregate all statistics up to HB level and produce a HB level index, instead of a local authority one.

**Comment by MikeJohnPage** [comment]
Additionally:

- Kidney Disease will need to be dropped if data or a proxy cannot be found
- Children's Social, Emotional and Mental Health will need to be dropped if updated data cannot be found (last data is 2013)
- For the missing values in Internet Access can we not leave this as `NA` and control for these in the building of the indices or impute the missing values based on a nearest neighbours approach?

**Comment by CatReid** [comment]
Thanks for working on this!
I would say in answer to point 1, these are indicators where they do not seem to be present (and therefore measured) in England's Health Index (based on the file here: https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandwellbeing/datasets/healthindexunderlyingdataengland) and methodology explanation here (https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/healthandwellbeing/methodologies/healthindexindicatorsanddefinitions). I checked to see if there were proxies and put them in the metadata already (e.g. cardiovascular conditions replacing atrial fibrillation, heart disease, arterial disease, stroke & TI as this was more in line with how England's HI recorded their data). Others, like children in state care, is not measured and there doesn't seem to be a proxy that's in line with this, so I would move to remove that from the metadata. However, happy to talk through everything more on Monday if that's better!

**Comment by MikeJohnPage** [comment]
@CatReid weren't Scotland's indicators based on Englands indicators, so how can they not be present in the English index? I think maybe I am missing something on this point.

**Comment by matthewgthomas** [comment]
**Health Board data needs aggregating to local authority data**
It's fine to apply the health board scores to the LAs sitting within it. This is similar in principle to how some IMD indicators are calculated, as well as an [LSOA-level version of the English Health Index](https://northumbriahealthindex.lcp.uk.com/).

**Comment by MikeJohnPage** [comment]
Okay got it. I think we have a clear path ahead now. Will keep you posted.

**Comment by MikeJohnPage** [comment]
Closing this issue and creating separate issues for the indicators which may need deleting.
