### ISSUE TITLE
Self harm

### ISSUE THREAD

**Issue by MikeJohnPage** [humaniverse/healthindexscotland#42]

**Comment by MikeJohnPage** [comment]
@CatReid Self harm statistics only appear to be available nationally in the links you put in the metadata?

**Comment by CatReid** [comment]
ah i didn't work on self-harm, that was Jenna. i just remember she said it wasn't at LA level the data

**Comment by MikeJohnPage** [comment]
Okay well it will have to be excluded from the analysis in that case.
