### ISSUE TITLE
Kidney Disease

### ISSUE THREAD

**Issue by MikeJohnPage** [humaniverse/healthindexscotland#43]

**Comment by MikeJohnPage** [comment]
There is incomplete data, noth at the health board level (11/14 areas contain data), and at the HSCP level (24/32 present).

See: https://publichealthscotland.scot/publications/general-practice-disease-prevalence-data-visualisation/general-practice-disease-prevalence-visualisation-27-june-2023/dashboard/

**Comment by matthewgthomas** [comment]
Closing this issue. We will live with the missing indicators.
